---
- name: Initialize k8s cluster on master node only
  command: kubeadm init --pod-network-cidr=10.244.0.0/16

- name: Setup kubeconfig for JPytlinski user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/JPytlinski/.kube
    - cp -i /etc/kubernetes/admin.conf /home/JPytlinski/.kube/config
    - chown JPytlinski:JPytlinski /home//JPytlinski/.kube/config

- name: Install Flannel on Master
  when: inventory_hostname in groups['k8s_master']
  command: kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml

- name: Generate join command 
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
 
