--- 
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add k8s GPG key 
  shell: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add k8s repo and install kubelet, kubeadm and kubectl 
  shell: | 
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl

- name: Delete config.toml for kubeadm to work
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart containerd
  systemd_service:
    state: restarted
    daemon_reload: true
    name: containerd

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}
    create: yes

- name: Restart kubelet
  service:
    name: kubelet 
    daemon_reload: yes
    state: restarted

