--- 
- name: Install system packages for Docker
  apt: 
    name: "{{ packages_for_docker }}"
    state: present 
    uptade_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages_docker }}"
    state: present 
    update_cache: yes


