---
- name: allow all port 8080 connections
  community.general.ufw:
    rule: allow
    port: 8080
    protocol: tcp

- name: allow all ssh connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: enable firewall and deny all traffic by default 
  community.general.ufw:
    state: enabled
    default: deny 
