---
- name: allow all port 8080 connections
  community.general.ufw:
    rule: allow
    name: open_8080

- name: allow all ssh connections
  community.general.ufw:
    rule: allow
    name: open_ssh

- name: enable firewall and deny all traffic by default 
  community.general.ufw:
    state: enabled
    default: deny 