---
- name: Set nopasswd sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create a new user with sudo privileges
  user: 
    name: "{{ created_username }}"
    state: present
    groups: sudo 
    append: true 
    create_home: true 
